rewrite ^/trx/([^/]+)/results /rpc/get_trx_results?trx_id=$1 break;
# endpoint for get /trx/{trx_id}/results

rewrite ^/nfts/by-trx/([^/]+) /rpc/get_nft_instances_by_trx?trx_id=$1 break;
# endpoint for get /nfts/by-trx/{trx_id}

rewrite ^/nfts/([^/]+)/([^/]+)/([^/]+) /rpc/get_nft_instances_with_tags?creator=$1&symbol=$2&tags=$3 break;
# endpoint for get /nfts/{creator}/{symbol}/{tags}

rewrite ^/nfts/([^/]+)/([^/]+) /rpc/get_nft_instances?creator=$1&symbol=$2 break;
# endpoint for get /nfts/{creator}/{symbol}

rewrite ^/nfts /rpc/get_nft_types break;
# endpoint for get /nfts

rewrite ^/sync-status /rpc/get_sync_status break;
# endpoint for get /sync-status

rewrite ^/version /rpc/get_version break;
# endpoint for get /version

rewrite ^/$ / break;
# endpoint for openapi spec itself

rewrite ^/(.*)$ /rpc/$1 break;
# default endpoint for everything else
